blank_issues_enabled: true
contact_links:
  - name: ðŸ¤” Ask a Question
    url: 'https://github.com/mlco2/ecologits/discussions/new?category=q-a'
    about: Ask a question about how to use EcoLogits using GitHub discussions
